donordesa/urls.py
from django.urls import path
from donordesa import views

app_name = 'donordesa'
urlpatterns = [
	path('', views.home, name='home'),
	path('home', views.home, name='home'),
]

web/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('donordesa.urls')),
]

donordesa/models.py
from django.db import models

# Create your models here.

donordesa/views.py
from django.shortcuts import render, redirect

# Create your views here.
def home(request):
	respons = {}
	return render(request, 'landing.html')

donordesa/templates/landing.html
{% extends "base.html" %}
{% load static %}

{% block content %}
     <!-- HEADER -->
	 <header class="masthead">
        <div class="container-fluid d-flex h-100 align-items-center">
            <div class="mx-auto text-center">
				<h1 class="text-white mx-auto my-100 line1"><strong>Selamat Datang di Games</strong></h1>
				<h1 class="text-white mx-auto my-0"><strong>Pesawat Kertas!</strong></h1>
            </div>
        </div>
    </header>
	
<body>
	<div class="hpg-content">
	    <div class="row text-center">
	        <div class="col-md-12 text-center">
	        	<div class="col-md-8 text-center" style="padding-top: 50px;">
	        			<img src="{% static 'img/pesawat.PNG' %}">
	        	</div>
	            <h1 class="judul-kartu">Games Apa Ini?</h1>
	        </div>
	    	<div class="col-md-12 text-center">
	            <div class="card border-dark mb-3 mx-auto" style="max-width: 30rem;">
	            	<p class="card-text"></p>
	            	<h5 class="card-title isi-kartu">Pesawat Kertas adalah sebuah permainan
 										   yang diadaptasi dari permainan tradisional 
 										   masyarakat Indonesia “Catur Jawa”</h5>
					<p class="card-text"></p>
	        	</div>
	    	</div>
	    </div>
	    <div class="row text-center">
	        <div class="col-md-12 text-center">
	        	<div class="col-md-10 text-left" style="padding-top: 50px; transform: rotateY(180deg);">
	        			<img src="{% static 'img/pesawat.PNG' %}">
	        	</div>
	            <h1 class="judul-kartu">Bagaimana cara mainnya?</h1>
	        </div>
	    	<div class="col-md-12 text-center">
	            <div class="card border-dark mb-3 mx-auto" style="max-width: 30rem;">
	            	<p class="card-text"></p>
	            	<h5 class="card-title isi-kartu">- Permainan dilakukan oleh 2 orang pemain.<br>
	            	- Masing-masing pemain mendapat 3 bidak.<br>
	            	- Pemain secara bergantian menggerakkan bidak.<br>
	            	- Pergerakan satu bidak yaitu 1 langkah ke posisi <br>
	            	yang sedang tidak ditempati oleh bidak lain.<br>
    				-  Pemain yang membuat garis lurus dengan 3 bidak<br>
    				terlebih dahulu keluar sebagai pemenang<br>
    				dan permainan berakhir.<br>
    				- Tiga spot bidak pada awal permainan tidak dapat <br>
    				dijadikan tempat membuat garis lurus.</h5>
					<p class="card-text"></p>
	        	</div>
	    	</div>
	    </div>
	    <div class="row text-center">
	        <div class="col-md-12 text-center">
	        	<div class="col-md-9 text-right">
	        	</div>
	        </div>
	    	<div class="col-md-8 text-right" style="padding-top: 70px">
	    		<a class="btn btn-outline-primary badge-pill btn-lg " style="padding-right: 2rem; padding-left: 2rem; " role="button" href="">Next </a>
	    	</div>
	    </div>
		<br><br><br>
	</div>
</body>

<script>
	function openNav() {
	 	document.getElementById("mySidepanel").style.width = "150px";
	}

	function closeNav() {
	 	document.getElementById("mySidepanel").style.width = "0";
	}
</script>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>DonorDesa</title>
    <link rel="icon" href="{% static 'img/logo.png' %}" type="image/gif">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'css/design.css' %}">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
 	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
	<script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
	<script src="{% static 'js/script.js' %}"></script>
</head>

<body>
	<!-- NAVBAR -->
	<nav class="navbar navbar-expand-lg navbar-light">
		<a class="navbar-brand active" href="#"><img src="{% static 'img/logo.png' %}" style="width:100px;"><span class="sr-only">(current)</span></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  	<span class="navbar-toggler-icon"></span>
		</button>
	  
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		  	<ul class="navbar-nav mr-auto">
				<li class="nav-item">
			 		 <a class="nav-link" href="{% url 'donordesa:home' %}">HOME</a>
				</li>
				<li class="nav-item">
			  		<a class="nav-link" href="">CAMPAIGN</a>
				</li>
				<li class="nav-item">
			  		<a class="nav-link" href="">NEWS</a>
				</li>
			</ul>

		</div>
	</nav>

    {% block content %}
	{% endblock %}
	
	<!-- FOOTER -->
	<footer id="myFooter">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 text-center">
					<br>
                    <img src="{% static 'img/mascot.PNG' %}" style="width:75%;">
                </div>
                <div class="col-sm-3" style="margin-left:10px; margin-right:10px;">
                    <h5>DonorDesa.com</h5>
                    <ul>
                        <li class="text-justify">Sebuah platform yang digunakan untuk menggalang dana masyarakat desa.</li>
                    </ul>
				</div>
                <div class="col-md-auto">
                    <h5></h5>
                    <ul>
						<li>Multi-Agent System	</li>
                        <li>Kelompok 4</li>
						<li>Sistem Cerdas - A</li>
						<li><a href="https://gitlab.com/airship-team/pesawat-kertas.git">Link Gitlab</a></li>
                    </ul>
				</div>
				<div class="col-auto"></div>
                <div class="col-md-auto">
                    <h5>Developer</h5>
                    <ul>
                        <li>Aulia Rosyida (1706025346)</li>
                        <li>Hana Raissya (1706979266)</li>
						<li>Mutia Rahmatun Husna (1706039622)</li>
						<li>Rahmat Fadhilah (1706074902)</li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
</body>

</html>